### ISSUE TITLE
Freecam's entity is visible when used with First Person Model mod

### ISSUE THREAD

**Issue by noah123586** [MinecraftFreecam/Freecam#185]
### Description of the issue

free cam will put me into a steve body or alex body and show them as if they where swimming

every time I enter freecam mode, it would put me into a steve or alex body.
![2024-03-08_12 28 10](https://github.com/MinecraftFreecam/Freecam/assets/162735184/4bad4627-f166-4eab-847f-8f140a62d23d)

### Expected behavior

the mod to work fine just as it did in the same version, just a different modpack

### Steps to reproduce

1. Open a singleplayer world
2. Enable Freecam by pressing `v`
3. ...

### How prevalent is the issue?

every time i turn on free cam

### Freecam version

1.2.3

### Are you using "Modrinth Edition"?

No

### Minecraft version

1.18.2

### Modding platform

- [ ] Fabric
- [ ] Neoforge
- [X] Forge

**Comment by MattSturgeon** [comment]
> just a different modpack

This sounds like a compatibility issue. What mods are you using?

If you can, please try disabling them one-at-a-time and reporting back which mod being disabled resolved the issue.

**Comment by 3ncanis** [comment]
Experiencing this as well, @noah123586 if you could post your mod list it would make determining which mod is causing the conflict much easier.

**Comment by MattSturgeon** [comment]
It'd be great if _both_ of you (and anyone else affected) could share what mods you're using.

This may help us narrow down the cause and investigate whether there's anything we can do to fix or work around the issue on our end.

**Comment by noah123586** [comment]
it's https://www.curseforge.com/minecraft/mc-mods/first-person-model sorry for taking so long to reply. i got rid of this mod and freecam worked fine.

**Comment by noah123586** [comment]
oop

**Comment by MattSturgeon** [comment]
> it's [FirstPersonModel](https://www.curseforge.com/minecraft/mc-mods/first-person-model) sorry for taking so long to reply. i got rid of this mod and freecam worked fine.

Interesting.

#50 and https://github.com/tr7zw/FirstPersonModel/issues/291 are apparently resolved, but there could've been a regression... Maybe when we switched to using the swimming pose?

**Comment by MattSturgeon** [comment]
@noah123586, I hope you don't mind, but I'm re-opening this as the bug still isn't fixed.

Feel free to unsubscribe if this issue no longer interests you:

![image](https://github.com/MinecraftFreecam/Freecam/assets/5046562/7cba1f70-4899-4c22-89fa-6e93500192bd)

**Comment by MattSturgeon** [comment]
To @AzuryxxVortex and anyone subscribed here: do you also get this issue with old versions of First Person Model and/or old versions of Freecam?

As this issue was supposedly fixed in [this commit](https://github.com/tr7zw/FirstPersonModel/commit/2f5ae9395f770b763f3f5f37a9af88f7a557f3b6) (which I think was first released in FFP v2.2.0), it'd be interesting to know if something they've done or something we've done has broken the compatibility.

**Comment by AzuryxxVortex** [comment]
> To @AzuryxxVortex and anyone subscribed here: do you also get this issue with old versions of First Person Model and/or old versions of Freecam?

I've not tested it before, but I will try to downgrade and see with all 3 versions of Freecam there currently is on Modrinth. See if it was on this side...

**Comment by AzuryxxVortex** [comment]
All three have the same issue, it wouldn't appear to be from there.
![image](https://github.com/MinecraftFreecam/Freecam/assets/112041895/b2e1134c-4d01-4e4e-9d49-9395f148edfc)

I'll attempt the other way around then.

**Comment by AzuryxxVortex** [comment]
Same issue persists across all versions of FPM, it seems to simply be broken for all of 1.20 and upwards I'd assume.

**Comment by AzuryxxVortex** [comment]
_Update_
The issue is only fixed on the Fabric version of FMP, but it persists in Forge.

**Comment by MattSturgeon** [comment]
Good work! It looks like FPM will need to extend their Freecam support to their Forge version too then.

While I don't think it's directly related, I should also highlight [this commit](https://github.com/MinecraftFreecam/Freecam/commit/5fc28c7ef28427e7b723bd936fd4b725dae116a1) added in Freecam v1.2.1 which works around a Forge quirk that broke our "show player" option.

Essentially, Forge prevents the player being rendering when viewed from Freecam, so we rendered the ourselves instead. This quirk isn't present in Neoforge or Fabric.

As above, I don't think this is related to this issue because we're explicitly rendering _the player_, not the `FreeCamera` entity.

**Comment by MattSturgeon** [comment]
FPM has fixed this in https://github.com/tr7zw/FirstPersonModel/commit/81c5124354a346624075d5878a9e8740f2baa34c, which I believe will make it into their next release.

Let me know if that doesn't work and I'll re-open this issue.

**Comment by AzuryxxVortex** [comment]
Tested it out, I can say that it works- Thanks!

**Comment by MattSturgeon** [comment]
> Tested it out, I can say that it works- Thanks!

Thanks for letting us know, but don't thank me - thank @tr7zw!
